server:
  port: 9090

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: ms-auth
          # lb = load balancer
          uri: lb://ms-auth
          predicates:
            - Path=/ms-auth/**
        - id: ms-post
          # lb = load balancer
          uri: lb://ms-post
          predicates:
            - Path=/ms-post/**
        - id: ms-comment
          # lb = load balancer
          uri: lb://ms-comment
          predicates:
            - Path=/ms-comment/**


eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
  client:
    register-with-eureka: true
    service-url:
      default-zone: localhost:8761/eureka

logging:
  level:
    ['org.springframework']: info
    ['it.cgmconsulting.gateway']: info

# CUSTOM PROPERTIES
application:
  security:
    token: ${TOKEN}
    internalToken: ${INTERNAL_TOKEN}